# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lunchrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
