# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lunchrequest',
            old_name='place',
            new_name='spokenlanguages',
        ),
        migrations.RemoveField(
            model_name='lunchrequest',
            name='time',
        ),
        migrations.AddField(
            model_name='lunchrequest',
            name='aboutyou',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunchrequest',
            name='lunchpreference',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunchrequest',
            name='university',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunchrequest',
            name='yoursubject',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
